server:  
  port: 9000

#spring:  
  #application:
    #name: core-service

eureka:  
  client:
    serviceUrl:
      defaultZone: http://192.168.0.103:8761/eureka/,http://192.168.0.103:8762/eureka/
  instance:
    preferIpAddress: true