server:  
  port: 7000

spring:  
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sinhasonalkumar/config-repo/
          #username:
          #password:  

eureka:  
  client:
    serviceUrl:
      defaultZone: http://172.18.128.206:8761/eureka/,http://172.18.128.206:8762/eureka/
  instance:
    preferIpAddress: true