server:  
  port: 8761

spring:  
  application:
    name: eureka

eureka:  
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.18.128.206:8761/eureka/,http://172.18.128.206:8762/eureka/