server:  
  port: 8001

#spring:  
  #application:
    #name: notification-service

eureka:  
  client:
    serviceUrl:
      defaultZone: http://172.18.128.206:8761/eureka/,http://172.18.128.206:8762/eureka/
  instance:
    preferIpAddress: true